### ISSUE TITLE
Pusta lekcja w Powtórka#2

### ISSUE THREAD

**Issue by WBigaj** [coders-school/qa-sessions#2]
W kategorii Przykłady oraz uwagi odnośnie Code Review nic się nie wyświetla. Kliknięcie linku na stronie kieruje na "error 404".
Analogicznie jest w kategoriach: "Scrum" , "Pytania z kanału #powtórka" oraz w "Wyniki konkursu STL"

![Pusta lekcja](https://user-images.githubusercontent.com/22654594/91533765-beea5c00-e910-11ea-88d2-561616f2cf10.png)
![Pusta lekcja2](https://user-images.githubusercontent.com/22654594/91533766-bf82f280-e910-11ea-87a2-eee6c3decddd.png)

**Comment by ziobron** [comment]
Fixed
